package View.login;

import Controlator.management_Login;
import Model.staff;
import Model.roles_per_user;
import com.mysql.cj.util.StringUtils;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class frm_SignUp extends javax.swing.JFrame {

    private int contador;
    private staff user = new staff();
    private roles_per_user roles_per_user = new roles_per_user();
    private management_Login manaLogin = new management_Login();

    public frm_SignUp() {

        JFrame.setDefaultLookAndFeelDecorated(true);

        initComponents();

        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        panel_Loging = new javax.swing.JPanel();
        cbxUser_type = new javax.swing.JComboBox<>();
        txtUser_id = new javax.swing.JTextField();
        txtlast_name = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        btn_SignUp = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_intentosFallidos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Password_field = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxUser_job = new javax.swing.JComboBox<>();
        btn_close = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign up");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Loging.setBackground(new java.awt.Color(0, 0, 0,80));
        panel_Loging.setForeground(new java.awt.Color(0, 0, 0));
        panel_Loging.setToolTipText("");
        panel_Loging.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cbxUser_type.setBackground(new java.awt.Color(0, 0, 0));
        cbxUser_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Worker", "Administrator" }));
        cbxUser_type.setSelectedItem(null);

        txtUser_id.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N

        txtlast_name.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N

        txtName.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N

        txtUsername.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N

        btn_SignUp.setBackground(new java.awt.Color(153, 153, 0));
        btn_SignUp.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        btn_SignUp.setForeground(new java.awt.Color(255, 255, 255));
        btn_SignUp.setText("sign up");
        btn_SignUp.setActionCommand("Sign up");
        btn_SignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignUpActionPerformed(evt);
            }
        });

        btn_Cancel.setBackground(new java.awt.Color(153, 153, 0));
        btn_Cancel.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        btn_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cancel.setText("Cancel");
        btn_Cancel.setActionCommand("Sign up");
        btn_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User profile:");

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");

        lb_intentosFallidos.setBackground(new java.awt.Color(0, 0, 0));
        lb_intentosFallidos.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        lb_intentosFallidos.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID:");

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pasword:");

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username");

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Last name");

        Password_field.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        Password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_fieldActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 153, 0));
        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tabacon Thermal Resort & Spa");
        jLabel2.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Workstation:");

        cbxUser_job.setBackground(new java.awt.Color(0, 0, 0));
        cbxUser_job.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Front Office Department.", "Engineering Department.", "Sales and Marketing Department.", "Information Technology (IT).", "Accounts and Credits Department." }));
        cbxUser_job.setSelectedItem(null);

        javax.swing.GroupLayout panel_LogingLayout = new javax.swing.GroupLayout(panel_Loging);
        panel_Loging.setLayout(panel_LogingLayout);
        panel_LogingLayout.setHorizontalGroup(
            panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LogingLayout.createSequentialGroup()
                .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_LogingLayout.createSequentialGroup()
                        .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_intentosFallidos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_LogingLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel1)))))
                        .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_LogingLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(cbxUser_job, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LogingLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxUser_type, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Password_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtlast_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUser_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LogingLayout.createSequentialGroup()
                                        .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(69, 69, 69)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_LogingLayout.setVerticalGroup(
            panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LogingLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlast_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxUser_type, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxUser_job, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_intentosFallidos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_LogingLayout.createSequentialGroup()
                        .addComponent(btn_SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Cancel)))
                .addGap(40, 40, 40))
        );

        getContentPane().add(panel_Loging, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 430, 510));

        btn_close.setBackground(new java.awt.Color(0, 0, 0));
        btn_close.setForeground(new java.awt.Color(0, 0, 0));
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Error_36910.png"))); // NOI18N
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 40, 40));

        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        Background.setFocusable(false);
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, 0, 1410, 600));

        setSize(new java.awt.Dimension(1068, 601));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_fieldActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        open_signIn();
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void btn_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignUpActionPerformed

        if ((validate_signUp_data().isEmpty())) {

            user.setId(Integer.parseInt(txtUser_id.getText()));

            user.setName(txtName.getText());

            user.setLast_name(txtlast_name.getText()); // cambiar el jtxt
            
            user.setUserName(txtUsername.getText());

            manaLogin.setPassword_logIN(user, Password_field.getPassword());
            
            user.setWorkstation(cbxUser_job.getSelectedItem().toString());

            int user_role_id = (cbxUser_type.getSelectedIndex() + 1);
            
            roles_per_user.setUser_id(user.getId());
            
            roles_per_user.setUser_role_id(user_role_id);

            if ((manaLogin.register_staff(user)) && (manaLogin.register_roles_per_staff(roles_per_user))) {

                JOptionPane.showMessageDialog(this, "Your accound was registered ", "Successfully logged up!", JOptionPane.INFORMATION_MESSAGE);

                open_signIn();
            }

        } else {

            JOptionPane.showMessageDialog(this, "EMPTY FIELDS:" + validate_signUp_data(), "You must fill in all fields!", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btn_SignUpActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    public javax.swing.JPasswordField Password_field;
    public javax.swing.JButton btn_Cancel;
    public javax.swing.JButton btn_SignUp;
    public javax.swing.JButton btn_close;
    public javax.swing.JComboBox<String> cbxUser_job;
    public javax.swing.JComboBox<String> cbxUser_type;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb_intentosFallidos;
    private javax.swing.JPanel panel_Loging;
    public javax.swing.JTextField txtName;
    public javax.swing.JTextField txtUser_id;
    public javax.swing.JTextField txtUsername;
    public javax.swing.JTextField txtlast_name;
    // End of variables declaration//GEN-END:variables

    public String validate_signUp_data() {

        String empty_fields = "";

        if (txtUser_id.getText().trim().isEmpty()) {

            txtUser_id.requestFocus();

            empty_fields += "\nUser id.";

        } else if (validate_format_user_id() == false) {
            
            
            JOptionPane.showMessageDialog(this, "Your 'ID' should only have numbers!", "Critical error:", JOptionPane.ERROR_MESSAGE);

            txtUser_id.setText("");
            
             empty_fields += "\nUser id.";

        }

        if (txtName.getText().isEmpty()) {

            txtName.requestFocus();

            empty_fields += "\nName.";

        }

        if (txtlast_name.getText().isEmpty()) {

            txtlast_name.requestFocus();

            empty_fields += "\nUsername.";

        } else if (manaLogin.verificate_username(txtlast_name.getText())) {

            JOptionPane.showMessageDialog(this, "this username is already exist! try again:", "Error!", JOptionPane.ERROR_MESSAGE);

            txtlast_name.setText("");

            empty_fields += "\nUsername.";

        }

        if (txtUsername.getText().isEmpty()) {

            txtUsername.requestFocus();

            empty_fields += "\nEmail.";

        }

        if (Password_field.getPassword().length == 0) {

            Password_field.requestFocus();

            empty_fields += "\nPassword.";

        }

        if (cbxUser_type.getSelectedItem() == null) {

            cbxUser_type.requestFocus();

            empty_fields += "\nUser type.";

        }
        
         if (cbxUser_job.getSelectedItem() == null) {

            cbxUser_type.requestFocus();

            empty_fields += "\nWorkstation.";

        }

        return empty_fields;
    }

    public void open_signIn() {

        this.dispose();

        frm_SignIn signIn = new frm_SignIn();

        signIn.setVisible(true);
    }

    public boolean validate_format_user_id() {

        boolean is_number = true;

        try {

         int test = Integer.parseInt(txtUser_id.getText());

        } catch (NumberFormatException e) {

            is_number = false;

        }

        return is_number;

    }
}
