/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controlator.management_reserve;
import Model.reservation;
import Model.rooms;

import java.awt.event.ItemEvent;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.ZoneId;

import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author mcortes19
 */
public class ifrm_reserve extends javax.swing.JInternalFrame {

    private int worker_id;
    private static rooms room;
    management_reserve management = new management_reserve();

    public ifrm_reserve(int staff_id) throws PropertyVetoException {
        initComponents();
        this.setMaximum(true);
        worker_id = staff_id;
        list_reservation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        win_reserve = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_Save = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        lb_customer_name = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        txt_subtotal = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        cbo_room_id = new javax.swing.JComboBox<>();
        cbo_customer_id = new javax.swing.JComboBox<>();
        spiner_kids_number = new javax.swing.JSpinner();
        spiner_adults_number = new javax.swing.JSpinner();
        date_departure = new com.toedter.calendar.JDateChooser();
        cbo_discount = new javax.swing.JComboBox<>();
        date_entry = new com.toedter.calendar.JDateChooser();
        cbo_way_to_pay = new javax.swing.JComboBox<>();
        txt_staff_id = new javax.swing.JTextField();
        txt_current_date = new javax.swing.JTextField();
        txt_reserved_days = new javax.swing.JTextField();
        btn_calculate_price = new javax.swing.JButton();
        btn_calculate_days = new javax.swing.JButton();
        panel_information_image = new javax.swing.JPanel();
        lb_room_number = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        txt_maximun_adults = new javax.swing.JTextField();
        txt_maximun_kids = new javax.swing.JTextField();
        txt_price_kid = new javax.swing.JTextField();
        txt_price_adult = new javax.swing.JTextField();
        lb_room_image = new javax.swing.JLabel();
        image_background = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btn_save = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_edit = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btn_delete = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btn_print = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btn_change_room = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btn_Check_in = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_cerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lb_total = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_reserve = new javax.swing.JTable();

        win_reserve.setMinimumSize(new java.awt.Dimension(942, 876));
        win_reserve.setPreferredSize(new java.awt.Dimension(942, 876));
        win_reserve.setSize(new java.awt.Dimension(942, 876));
        win_reserve.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                win_reserveWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                win_reserveWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                win_reserveWindowOpened(evt);
            }
        });
        win_reserve.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );

        win_reserve.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 20, 860));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102,80));

        btn_Save.setBackground(new java.awt.Color(153, 153, 0));
        btn_Save.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        btn_Save.setForeground(new java.awt.Color(255, 255, 255));
        btn_Save.setText("Save");
        btn_Save.setActionCommand("Sign up");
        btn_Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        Cancel.setBackground(new java.awt.Color(153, 153, 0));
        Cancel.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        Cancel.setForeground(new java.awt.Color(255, 255, 255));
        Cancel.setText("Cancel");
        Cancel.setActionCommand("Sign up");
        Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        lb_customer_name.setBackground(new java.awt.Color(0, 0, 0));
        lb_customer_name.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        lb_customer_name.setForeground(new java.awt.Color(153, 153, 0));
        lb_customer_name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb_customer_name.setOpaque(true);

        jLabel64.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel64.setText("Discount");

        jLabel59.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel59.setText("Room ID");

        jLabel65.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel65.setText("Staff ID");

        jLabel70.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel70.setText("customer ID");

        jLabel66.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel66.setText("Way to pay");

        jLabel68.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel68.setText("adults number");

        jLabel67.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel67.setText("kids number");

        jLabel69.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel69.setText("Entry date");

        jLabel71.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel71.setText("Current date");

        jLabel72.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel72.setText("Reserved days");

        jLabel73.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel73.setText("Departure date");

        txt_subtotal.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txt_subtotal.setForeground(new java.awt.Color(0, 0, 0));

        jLabel74.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel74.setText("Total:");

        jLabel75.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel75.setText("Sub-total:");

        txt_total.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txt_total.setForeground(new java.awt.Color(0, 0, 0));

        cbo_room_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------------------------" }));
        cbo_room_id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_room_idItemStateChanged(evt);
            }
        });

        cbo_customer_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------------------------" }));
        cbo_customer_id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_customer_idItemStateChanged(evt);
            }
        });
        cbo_customer_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_customer_idActionPerformed(evt);
            }
        });

        cbo_way_to_pay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debit card.", "Credit card.", "Cash.", "electronic wallets.", "virtual payments." }));
        cbo_way_to_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_way_to_payActionPerformed(evt);
            }
        });

        txt_staff_id.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txt_staff_id.setForeground(new java.awt.Color(0, 0, 0));

        txt_current_date.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txt_current_date.setForeground(new java.awt.Color(0, 0, 0));

        txt_reserved_days.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        txt_reserved_days.setRequestFocusEnabled(false);

        btn_calculate_price.setBackground(new java.awt.Color(153, 153, 0));
        btn_calculate_price.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        btn_calculate_price.setForeground(new java.awt.Color(255, 255, 255));
        btn_calculate_price.setText("Calculate");
        btn_calculate_price.setActionCommand("Sign up");
        btn_calculate_price.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_calculate_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculate_priceActionPerformed(evt);
            }
        });

        btn_calculate_days.setBackground(new java.awt.Color(153, 153, 0));
        btn_calculate_days.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        btn_calculate_days.setForeground(new java.awt.Color(255, 255, 255));
        btn_calculate_days.setText("Calculate");
        btn_calculate_days.setActionCommand("Sign up");
        btn_calculate_days.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_calculate_days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculate_daysActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel74)
                    .addComponent(jLabel75))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_subtotal)
                    .addComponent(txt_total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_calculate_price)
                .addGap(45, 45, 45))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel68)
                    .addComponent(jLabel71)
                    .addComponent(jLabel70)
                    .addComponent(jLabel66)
                    .addComponent(jLabel59)
                    .addComponent(jLabel65)
                    .addComponent(jLabel67)
                    .addComponent(jLabel69)
                    .addComponent(jLabel73)
                    .addComponent(jLabel72)
                    .addComponent(jLabel64))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_departure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbo_way_to_pay, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_reserved_days)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_calculate_days))
                    .addComponent(spiner_adults_number, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spiner_kids_number, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date_entry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbo_room_id, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                .addComponent(cbo_customer_id, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                .addComponent(txt_staff_id, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_current_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(cbo_discount, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_current_date, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_staff_id, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_customer_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_room_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_way_to_pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiner_adults_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiner_kids_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date_entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_departure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_reserved_days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_calculate_days))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btn_calculate_price, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(btn_Save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cancel)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        win_reserve.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 420, 860));

        panel_information_image.setBackground(new java.awt.Color(255, 255, 255,80));

        lb_room_number.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        lb_room_number.setText("Room number #");

        jLabel60.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel60.setText("Maximun adults");

        jLabel61.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel61.setText("Maximun kids");

        jLabel62.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel62.setText("Price per adult");

        jLabel63.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel63.setText("Price per kid");

        txt_maximun_adults.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        txt_maximun_adults.setRequestFocusEnabled(false);

        txt_maximun_kids.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        txt_maximun_kids.setRequestFocusEnabled(false);

        txt_price_kid.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        txt_price_kid.setRequestFocusEnabled(false);

        txt_price_adult.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        txt_price_adult.setRequestFocusEnabled(false);

        javax.swing.GroupLayout panel_information_imageLayout = new javax.swing.GroupLayout(panel_information_image);
        panel_information_image.setLayout(panel_information_imageLayout);
        panel_information_imageLayout.setHorizontalGroup(
            panel_information_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_information_imageLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lb_room_number)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_information_imageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_information_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel61)
                    .addComponent(jLabel63)
                    .addComponent(jLabel62)
                    .addComponent(jLabel60))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_information_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_information_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_price_kid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(txt_price_adult, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_maximun_kids))
                    .addComponent(txt_maximun_adults, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(266, 266, 266))
        );
        panel_information_imageLayout.setVerticalGroup(
            panel_information_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_information_imageLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lb_room_number)
                .addGap(63, 63, 63)
                .addGroup(panel_information_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maximun_adults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(panel_information_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maximun_kids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(panel_information_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_price_adult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(panel_information_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_price_kid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        win_reserve.getContentPane().add(panel_information_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 290, 550));
        win_reserve.getContentPane().add(lb_room_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 290, 310));

        image_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/room.jpg"))); // NOI18N
        win_reserve.getContentPane().add(image_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 880));

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reserve");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reservado.png"))); // NOI18N

        jToolBar2.setBackground(new java.awt.Color(102, 102, 102));
        jToolBar2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar2.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excel.png"))); // NOI18N
        jButton1.setText("Exel");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        jToolBar1.setRollover(true);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_save.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/document-add_114467.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.setFocusable(false);
        btn_save.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_save.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_save);
        jToolBar1.add(jSeparator1);

        btn_edit.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/document-edit_114472.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.setFocusable(false);
        btn_edit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_edit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_edit);
        jToolBar1.add(jSeparator4);

        btn_delete.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1486504830-delete-dustbin-empty-recycle-recycling-remove-trash_81361.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setFocusable(false);
        btn_delete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_delete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_delete);
        jToolBar1.add(jSeparator5);

        btn_print.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/printer_78349.png"))); // NOI18N
        btn_print.setText("Print");
        btn_print.setFocusable(false);
        btn_print.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_print.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_print);
        jToolBar1.add(jSeparator3);

        btn_change_room.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        btn_change_room.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exchange.png"))); // NOI18N
        btn_change_room.setText("Change room");
        btn_change_room.setFocusable(false);
        btn_change_room.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_change_room.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_change_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_change_roomActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_change_room);
        jToolBar1.add(jSeparator6);

        btn_Check_in.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        btn_Check_in.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/invoice_106601.png"))); // NOI18N
        btn_Check_in.setText("Check in");
        btn_Check_in.setFocusable(false);
        btn_Check_in.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Check_in.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Check_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Check_inActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_Check_in);
        jToolBar1.add(jSeparator2);

        btn_cerrar.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
        btn_cerrar.setText("Close");
        btn_cerrar.setFocusable(false);
        btn_cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_cerrar);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lb_total.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lb_total, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        table_reserve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "reservation_id", "room_id", "discount_id", "staff_id", "customer_id", "way_to_pay", "adults_number", "kids_number", "current_date", "entry_date", "departure_date", "reserved_days"
            }
        ));
        jScrollPane1.setViewportView(table_reserve);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1215, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_change_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_change_roomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_change_roomActionPerformed

    private void btn_Check_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Check_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Check_inActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        win_reserve.setTitle("Make reservation");
        win_reserve.setLocationRelativeTo(null);
        win_reserve.setVisible(true);
    }//GEN-LAST:event_btn_saveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed

        if ((validate_data().isEmpty())) {

            reservation reserve = new reservation();
            
            int customer_id, room_id, discount;
            
            String temp_discount;
            temp_discount  = cbo_discount.getSelectedItem().toString();
            String departure_date;
            String entry_date;
            
             SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

             entry_date = (format.format(date_entry.getDate()));
             departure_date = (format.format(date_departure.getDate()));

            
            customer_id = Integer.parseInt(cbo_customer_id.getSelectedItem().toString());
            
            room_id = Integer.parseInt(cbo_room_id.getSelectedItem().toString());
            
            discount = Integer.parseInt(temp_discount.substring(0, temp_discount.length() - 1));
            
            
            reserve.setStaff_id(Integer.parseInt(txt_staff_id.getText()));
            
            reserve.setCustomer_id(customer_id);
            
            reserve.setRoom_id(room_id);
            
            reserve.setWay_to_pay(cbo_way_to_pay.getSelectedItem().toString());
            
            reserve.setAdults_number((int) spiner_adults_number.getValue());
            
            reserve.setKids_number((int) spiner_kids_number.getValue());
            
            reserve.setEntry_date(entry_date);
            
            reserve.setDeparture_date(departure_date);
            
            reserve.setReserved_days(Integer.parseInt(txt_reserved_days.getText()));
            
            reserve.setDiscount_id(discount);
            

            if (management.register_reserve_room(reserve)) {

                JOptionPane.showMessageDialog(win_reserve, "Your reserve was registered ", "Reserved!!!", JOptionPane.INFORMATION_MESSAGE);

            }else{
                
                JOptionPane.showMessageDialog(win_reserve, "The reservation can't be saved ", "Eror!!!", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {

            JOptionPane.showMessageDialog(win_reserve, "EMPTY FIELDS:" + validate_data(), "You must fill in all fields!", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        win_reserve.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void cbo_way_to_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_way_to_payActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_way_to_payActionPerformed

    private void win_reserveWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_win_reserveWindowActivated
        initialize_default_fields();


    }//GEN-LAST:event_win_reserveWindowActivated

    private void cbo_customer_idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_customer_idItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {

            String customer_id = cbo_customer_id.getSelectedItem().toString();

            lb_customer_name.setText(management.search_customer_name(customer_id));
            
            lb_customer_name.setVisible(true);
        }

    }//GEN-LAST:event_cbo_customer_idItemStateChanged

    private void cbo_customer_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_customer_idActionPerformed

    }//GEN-LAST:event_cbo_customer_idActionPerformed

    private void cbo_room_idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_room_idItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {

            int room_id = Integer.parseInt(cbo_room_id.getSelectedItem().toString());

            room = management.search_room(room_id);

            fill_room_panel_fields(room);

            set_spiner(spiner_adults_number, room.getMaximun_adults());
            set_spiner(spiner_kids_number, room.getMaximun_kids());

            spiner_adults_number.setEnabled(true);
            spiner_kids_number.setEnabled(true);

        }
    }//GEN-LAST:event_cbo_room_idItemStateChanged

    private void win_reserveWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_win_reserveWindowOpened
        initialize_default_fields();
        fill_customers_id();
        fill_room_id();
        fill_discound();
        lb_room_image.setVisible(false);
        panel_information_image.setVisible(false);
        spiner_adults_number.setEnabled(false);
        spiner_kids_number.setEnabled(false);
        txt_subtotal.setEditable(false);
        txt_total.setEditable(false);
        txt_reserved_days.setEditable(false);
        lb_customer_name.setVisible(false);
        
    }//GEN-LAST:event_win_reserveWindowOpened

    private void btn_calculate_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculate_priceActionPerformed

        if (validate_data_price().isEmpty()) {

            Double price_kid = Double.parseDouble(txt_price_kid.getText());
            Double price_adult = Double.parseDouble(txt_price_adult.getText());
            int days_reserved = Integer.parseInt(txt_reserved_days.getText());
            String discount = (String) cbo_discount.getSelectedItem();

            Double total_price_kids = (price_kid * days_reserved);
            Double total_price_adults = (price_adult * days_reserved);
            Double total_discount = (Double.parseDouble(discount.substring(0, discount.length() - 1)) / 100); // elimina el ultimo charr del descuanto   (%) y lo convierte a entero

            Double sub_total_price = (total_price_adults + total_price_kids);

            Double total_price = sub_total_price - (sub_total_price * total_discount);

            txt_subtotal.setText(String.valueOf(sub_total_price));

            txt_total.setText(String.valueOf(total_price));

        } else {

            JOptionPane.showMessageDialog(win_reserve, "To make this operation is necesary: " + validate_data_price(), "Missing fields", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btn_calculate_priceActionPerformed

    private void btn_calculate_daysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculate_daysActionPerformed

        if (date_departure.getDate() == null || date_entry.getDate() == null) {

            JOptionPane.showMessageDialog(win_reserve, "You should fill all fields dates \nEntry date. \nDeparture date.", "Missing fields", JOptionPane.ERROR_MESSAGE);

        } else if (date_entry.getDate().after(date_departure.getDate()) || (date_entry.getDate().equals(date_departure.getDate()))) {

            JOptionPane.showMessageDialog(win_reserve, "Entry date should be before of departure date ", "Date error", JOptionPane.ERROR_MESSAGE);

        } else {

            LocalDateTime from = LocalDateTime.ofInstant(date_entry.getDate().toInstant(), ZoneId.systemDefault());
            LocalDateTime to = LocalDateTime.ofInstant(date_departure.getDate().toInstant(), ZoneId.systemDefault());
            // validar que las 2 fechas esten ingresadas
            Duration d = Duration.between(from, to);

            String reserved_days = String.valueOf(d.toDays());

            txt_reserved_days.setText(reserved_days);

        }

    }//GEN-LAST:event_btn_calculate_daysActionPerformed

    private void win_reserveWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_win_reserveWindowClosed
        clean_fields();
    }//GEN-LAST:event_win_reserveWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Cancel;
    private javax.swing.JButton btn_Check_in;
    public javax.swing.JButton btn_Save;
    public javax.swing.JButton btn_calculate_days;
    public javax.swing.JButton btn_calculate_price;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_change_room;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cbo_customer_id;
    private javax.swing.JComboBox<String> cbo_discount;
    private javax.swing.JComboBox<String> cbo_room_id;
    private javax.swing.JComboBox<String> cbo_way_to_pay;
    private com.toedter.calendar.JDateChooser date_departure;
    private com.toedter.calendar.JDateChooser date_entry;
    private javax.swing.JLabel image_background;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lb_customer_name;
    private javax.swing.JLabel lb_room_image;
    private javax.swing.JLabel lb_room_number;
    private javax.swing.JLabel lb_total;
    private javax.swing.JPanel panel_information_image;
    private javax.swing.JSpinner spiner_adults_number;
    private javax.swing.JSpinner spiner_kids_number;
    private javax.swing.JTable table_reserve;
    private javax.swing.JTextField txt_current_date;
    private javax.swing.JTextField txt_maximun_adults;
    private javax.swing.JTextField txt_maximun_kids;
    private javax.swing.JTextField txt_price_adult;
    private javax.swing.JTextField txt_price_kid;
    private javax.swing.JTextField txt_reserved_days;
    private javax.swing.JTextField txt_staff_id;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_total;
    private javax.swing.JDialog win_reserve;
    // End of variables declaration//GEN-END:variables

    public void initialize_default_fields() {
        Date date_of_today = new Date();

        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

        txt_current_date.setText(format.format(date_of_today));

        txt_current_date.setEditable(false);

        txt_staff_id.setText(String.valueOf(worker_id));

        txt_staff_id.setEditable(false);

    }

    public void fill_customers_id() {

        management.fill_combo_customer(cbo_customer_id);

        cbo_customer_id.setSelectedItem(null);
    }

    public void fill_room_id() {
        management.fill_combo_rooms(cbo_room_id);

        cbo_room_id.setSelectedItem(null);
    }

    public void fill_discound() {
        management.fill_combo_discount(cbo_discount);

        cbo_discount.setSelectedItem(null);
    }

    public void fill_room_panel_fields(rooms temp_room) {

        try {
            String room_id = String.valueOf(temp_room.getRoom_id());
            String maximun_adults = String.valueOf(temp_room.getMaximun_adults());
            String maximun_kids = String.valueOf(temp_room.getMaximun_kids());
            String price_adult = String.valueOf(temp_room.getPrice_per_day_adults());
            String price_kids = String.valueOf(temp_room.getPrice_per_day_kids());
            String dir = System.getProperty("user.dir") + "/src/rooms_img/" + temp_room.getImage();

            lb_room_number.setText("Room number " + room_id);
            txt_maximun_adults.setText(maximun_adults);
            txt_maximun_kids.setText(maximun_kids);
            txt_price_adult.setText(price_adult);
            txt_price_kid.setText(price_kids);

            management.resize_image_room(dir, lb_room_image);

            lb_room_image.setVisible(true);
            panel_information_image.setVisible(true);

        } catch (IOException ex) {

            Logger.getLogger(ifrm_reserve.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void set_spiner(JSpinner spiner, int maximun) {

        @SuppressWarnings("deprecation")

        SpinnerNumberModel model = new SpinnerNumberModel(
                new Integer(1), // Dato visualizado al inicio en el spinner
                new Integer(0), // Límite inferior
                new Integer(maximun), // Límite superior
                new Integer(1) // incremento-decremento
        );

        spiner.setModel(model);

    }

    public String validate_data_price() {
        String empty_fields = "";

        if (cbo_room_id.getSelectedItem() == null) {

            cbo_room_id.requestFocus();

            empty_fields += "\nRoom id.";
        }

        if (txt_reserved_days.getText().isEmpty()) {

            btn_calculate_days.requestFocus();

            empty_fields += "\nReserved days";
        }

        if (cbo_discount.getSelectedItem() == null) {

            cbo_discount.requestFocus();

            empty_fields += "\n Discount";

        }

        return empty_fields;
    }
    
    public String validate_data(){
        String empty_fields = "";
        
        if (cbo_customer_id.getSelectedItem() == null) {
            
            cbo_customer_id.requestFocus();
            
            empty_fields += "\n Customer ID";
            
        }
        
        if (cbo_room_id.getSelectedItem() == null) {
            
            cbo_room_id.requestFocus();
            
            empty_fields += "\n Room ID";
            
        }
        
        if (cbo_way_to_pay.getSelectedItem() == null) {
            
            cbo_way_to_pay.requestFocus();
            
            empty_fields += "\nWay to pay";
            
        }
        
        if (spiner_adults_number.getValue().equals("1")) {
            
            spiner_adults_number.requestFocus();
            
            empty_fields += "\nAs least one adult";
        }
        
        if (txt_reserved_days.getText().isEmpty()) {
            
            btn_calculate_days.requestFocus();
            
            empty_fields += "\nReserved days";
            
        }
        
        if (cbo_discount.getSelectedItem() == null) {
            
            cbo_discount.requestFocus();
            
            empty_fields += "\nDiscount";
            
        }
        
        if (txt_total.getText().isEmpty()) {
            
            btn_calculate_price.requestFocus();
            
            empty_fields  += "Price fields";
            
            
        }
        
        
        return empty_fields;
    }
    
    public void clean_fields(){
        txt_current_date.setText("");
        
        txt_staff_id.setText("");
        
        cbo_customer_id.setSelectedItem(null);
        
        cbo_room_id.setSelectedItem(null);
        
        cbo_way_to_pay.setSelectedItem(null);
        
        spiner_adults_number.setValue(1);
        
        spiner_kids_number.setValue(1);
        
        date_entry.setDate(null);
        
        date_departure.setDate(null);
        
        txt_reserved_days.setText("");
        
        cbo_discount.setSelectedItem(null);
        
        txt_subtotal.setText("");
        
        txt_total.setText("");
        
        lb_room_image.setVisible(false);
        
        panel_information_image.setVisible(false);
        
        lb_customer_name.setVisible(false);
        
        
    }
    
    public void list_reservation(){
        management.load_table(table_reserve, lb_total);
    }
}
