/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.login;

import Controlador.management_Login;
import Modelo.staff;
import Vista.Menu;
import java.awt.Color;
import javax.swing.JOptionPane;

public class frm_SignIn extends javax.swing.JFrame {

    private int contador;
    private staff user = new staff();
    private management_Login manaLogin = new management_Login();

    public frm_SignIn() {
        initComponents();
        

        //this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_close = new javax.swing.JButton();
        panel_Loging = new javax.swing.JPanel();
        txt_userName = new javax.swing.JTextField();
        btn_SignUp_go = new javax.swing.JButton();
        btn_SignIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_intentosFallidos = new javax.swing.JLabel();
        Password_field = new javax.swing.JPasswordField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_close.setBackground(new java.awt.Color(0, 0, 0));
        btn_close.setForeground(new java.awt.Color(0, 0, 0));
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Error_36910.png"))); // NOI18N
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(996, 0, 40, 40));

        panel_Loging.setBackground(new java.awt.Color(0, 0, 0,80));
        panel_Loging.setForeground(new java.awt.Color(0, 0, 0));
        panel_Loging.setToolTipText("");
        panel_Loging.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txt_userName.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txt_userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userNameActionPerformed(evt);
            }
        });

        btn_SignUp_go.setBackground(new java.awt.Color(153, 153, 0));
        btn_SignUp_go.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        btn_SignUp_go.setForeground(new java.awt.Color(255, 255, 255));
        btn_SignUp_go.setText("sign up");
        btn_SignUp_go.setActionCommand("Sign up");
        btn_SignUp_go.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_SignUp_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignUp_goActionPerformed(evt);
            }
        });

        btn_SignIn.setBackground(new java.awt.Color(153, 153, 0));
        btn_SignIn.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        btn_SignIn.setForeground(new java.awt.Color(255, 255, 255));
        btn_SignIn.setText("Sign in");
        btn_SignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_SignIn.setFocusTraversalPolicyProvider(true);
        btn_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignInActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pasword:");

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username:");

        jLabel2.setBackground(new java.awt.Color(153, 153, 0));
        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tabacon Thermal Resort & Spa");
        jLabel2.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("You are not registered yet? ");

        lb_intentosFallidos.setBackground(new java.awt.Color(0, 0, 0, 100));
        lb_intentosFallidos.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        lb_intentosFallidos.setForeground(new java.awt.Color(0, 0, 0));

        Password_field.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N

        javax.swing.GroupLayout panel_LogingLayout = new javax.swing.GroupLayout(panel_Loging);
        panel_Loging.setLayout(panel_LogingLayout);
        panel_LogingLayout.setHorizontalGroup(
            panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LogingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_LogingLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_LogingLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_userName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78))
            .addGroup(panel_LogingLayout.createSequentialGroup()
                .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_intentosFallidos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel_LogingLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SignUp_go, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(141, 141, 141))
        );
        panel_LogingLayout.setVerticalGroup(
            panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LogingLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(panel_LogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btn_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_SignUp_go)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_intentosFallidos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(panel_Loging, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 430, 370));

        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        Background.setFocusable(false);
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, -20, 1970, 920));

        setSize(new java.awt.Dimension(1036, 597));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btn_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignInActionPerformed

        if (validat_signin_data().isEmpty()) {

            user.setUserName(txt_userName.getText());

            manaLogin.setPassword_logIN(user, Password_field.getPassword());

            if (manaLogin.validate_accound(user)) {
                
                manaLogin.getUser(user);

                contador = 0;

                JOptionPane.showMessageDialog(this, "welcome to Tabacon Thermal Resort & Spa", "Successfully logged in!", JOptionPane.INFORMATION_MESSAGE);
                
                Menu menu = new Menu(user);
                
                this.setVisible(false);
                
                menu.setVisible(true);

            } else {

                contador = contador + 1;

                JOptionPane.showMessageDialog(this, "Your username or password are wrong, try again", "Login denied!", JOptionPane.ERROR_MESSAGE);

                if (contador == 1) {

                    lb_intentosFallidos.setForeground(Color.GREEN);

                    lb_intentosFallidos.setText("Failed attempts: " + contador);

                } else if (contador == 2) {

                    lb_intentosFallidos.setForeground(Color.YELLOW);

                    lb_intentosFallidos.setText("Failed attempts: " + contador);

                } else {

                    this.dispose();

                }
            }
    }//GEN-LAST:event_btn_SignInActionPerformed
       else {
    

            JOptionPane.showMessageDialog(this, "EMPTY FIELDS:" + validat_signin_data(), "You must fill in all fields!", JOptionPane.ERROR_MESSAGE);

        }
    }
    private void btn_SignUp_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignUp_goActionPerformed
        open_signUp();
    }//GEN-LAST:event_btn_SignUp_goActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void txt_userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userNameActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    public javax.swing.JPasswordField Password_field;
    public javax.swing.JButton btn_SignIn;
    public javax.swing.JButton btn_SignUp_go;
    public javax.swing.JButton btn_close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel lb_intentosFallidos;
    private javax.swing.JPanel panel_Loging;
    public javax.swing.JTextField txt_userName;
    // End of variables declaration//GEN-END:variables

    public void open_signUp() {
        this.dispose();

        frm_SignUp signUp = new frm_SignUp();

        signUp.setVisible(true);

    }

    public String validat_signin_data() {

        String empty_fields = "";

        if (txt_userName.getText().trim().isEmpty()) {

            txt_userName.requestFocus();

            empty_fields += "\nUsername.";

        }

        if (Password_field.getPassword().length == 0) {

            Password_field.requestFocus();

            empty_fields += "\nPassword.";

        }
        return empty_fields;
    }
}
